### ISSUE TITLE
Getting the following error when I am using lordofthejars in Spring boot application 

### ISSUE THREAD

**Issue by prabhakar349** [lordofthejars/nosql-unit#144]
I am getting the following error when trying to use 	nosqlunit-mongodb , version 0.8.1

Also @UsingDataSet is noy importing the data.	
```
  2015-10-08 15:14:21.482  INFO   --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2015-10-08 15:14:21.504  INFO   --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	... 3 common frames omitted    
```
```

I have added the following two lines in the TestCase class
   @ClassRule
    public static InMemoryMongoDb inMemoryMongoDb = newInMemoryMongoDbRule().build();
```

    @Rule
    public MongoDbRule mongoDbRule = newMongoDbRule().defaultSpringMongoDb("test");

Also I have the following configuration in spring context

	<bean name="fongo" class="com.github.fakemongo.Fongo">
		<constructor-arg value="InMemoryMongo" />
	</bean>
	<bean id="mongo" factory-bean="fongo" factory-method="getMongo" />
	
	<bean id="mongoTemplate"
 class="org.springframework.data.mongodb.core.MongoTemplate">
 <constructor-arg ref="mongo" />
 <constructor-arg name="databaseName" value="test" />
 </bean>

**Comment by joergreichert** [comment]
With the following I was able to overcome the connection issue
```java
    @Rule
    public MongoDbRule mongoDbRule = getSpringMongoDbRule();

    private SpringMongoDbRule getSpringMongoDbRule() {
        MongoDbConfiguration mongoDbConfiguration = new MongoDbConfiguration();
        mongoDbConfiguration.setDatabaseName("mydb");
        MongoClient mongo = MockMongoClient.create(new Fongo("test"));
        mongoDbConfiguration.setMongo(mongo);
        return new SpringMongoDbRule(mongoDbConfiguration);
    }
```

The problem is, that newMongoDbRule().defaultSpringMongoDb("mydb") calls internally MongoDbConfigurationBuilder.build that creates an instance of MongoClient, what is wrong when using Fongo, as then MockMongoClient should be used.

**Comment by lordofthejars** [comment]
Yes, this is the expected behaviour for now, to use Fongo, or define the
Fongo instance inside your Spring xml.

El dj., 3 març 2016 a les 16:40, Jörg Reichert (<notifications@github.com>)
va escriure:

**Comment by schorke** [comment]
I have the same issue and @joergreichert 's solution didn't work for me. My tests are running but I got this error in log :

```
2016-09-27 10:52:08.726 INFO  --- [main           ]                         org.mongodb.driver.cluster : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=50}
2016-09-27 10:52:08.727 INFO  --- [localhost:27017]                         org.mongodb.driver.cluster : Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	... 3 common frames omitted
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.068 sec - in com.comp.fongotest.dao.AccountDaoRepositoryTest
```

I am working with SpringBoot (Maven), Fongo and nosqlunit.

My test AccountDaoRepositoryTest.java : 

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {Application.class, DaoUnitTestApplicationConfig.class})
public class AccountDaoRepositoryTest {

    @Autowired
    private ApplicationContext applicationContext;

//    I tried this, see SpringMongoDbRule bean in DaoUnitTestApplicationConfig.java below
//    @Autowired
//    public SpringMongoDbRule springMongoDbRule;
//    @Rule
//    public MongoDbRule mongoDbRule = springMongoDbRule;

    @Rule
    public MongoDbRule mongoDbRule = newMongoDbRule().defaultSpringMongoDb("testdb");

    @Autowired
    private AccountDaoRepository accountDaoRepository;

    /**
     * Insert data from "five-account.json" and test count method
     */
    @Test
    @UsingDataSet(locations = "five-account.json", loadStrategy = LoadStrategyEnum.CLEAN_INSERT)
    public void countAllAccounts() {
        long total = accountDaoRepository.count();
        Assert.assertEquals(5, total);
}
```

My config DaoUnitTestApplicationConfig.java :

```java
@Configuration
@ComponentScan(basePackageClasses = { AccountDaoRepository.class })
@PropertySource("classpath:application-test.properties")
//@EnableMongoRepositories   //errors when added
//@ComponentScan(basePackages = "com.comp.fongotest") //no change when added
public abstract class DaoUnitTestApplicationConfig extends AbstractMongoConfiguration {

    @Override
    protected String getDatabaseName() {
        return "testdb";
    }

    @Bean
    @Override
    public Mongo mongo() throws Exception {
        return new Fongo("mongotest").getMongo();
    }

//     I tried with this like @joergreichert 
//    @Bean
//    public SpringMongoDbRule springMongoDbRule() {
//        MongoDbConfiguration mongoDbConfiguration = new MongoDbConfiguration();
//        mongoDbConfiguration.setDatabaseName(getDatabaseName());
//        try {
//            mongoDbConfiguration.setMongo(mongo());
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//        return new SpringMongoDbRule(mongoDbConfiguration);
//    }
}
```


If I use @joergreichert solution, I got this error : 

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.895 sec <<< FAILURE! - in com.comp.fongotest.dao.AccountDaoRepositoryTest
countAllAccounts(com.comp.fongotest.dao.AccountDaoRepositoryTest)  Time elapsed: 0.087 sec  <<< FAILURE!
java.lang.AssertionError: expected:<5> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.comp.fongotest.dao.AccountDaoRepositoryTest.countAllAccounts(AccountDaoRepositoryTest.java:48)
```
==> The annotation @UsingDataSet does not place data in the right Fongo or something...

Any help?

**Comment by choda** [comment]
Thank you joergreichert, you're solution helped me get rid of this annoying exception.

For the record, I only needed to import

```
<bean name="fongo" class="com.github.fakemongo.Fongo">
    <constructor-arg value="InMemoryMongo" />
</bean>
<bean id="mongo" factory-bean="fongo" factory-method="getMongo" />
```

(not the mongotemplate bean) in my application context, like this: 

```
@Configuration
@ImportResource("classpath:/nosql-unit.xml")
public class TestConfiguration {
    
}
```

and add your custom rule to the test class.


Does anyone know how to convert the xml beans the beans as annotated methods? I'm guessing something like:
```
@Bean
public Fongo fongo() {
    return new Fongo("inMemoryMongo");
}
```  
for the first one, but I'm confused by the factory-bean and factory-method parameters of the second bean.

**Comment by schorke** [comment]
Thanks @joergreichert for your solution! It helped me a lot!

**Comment by lordofthejars** [comment]
Thank you so much for your collaboration, @joergreichert @choda If you have time and want, you can update MongoDB documentation showing how to use Spring Boot and NoSQLUnit :)

**Comment by choda** [comment]
Found it! One can extend AbstractMongoConfiguration and get rid of the xml bean definitions:

```
@Configuration
public class MongoConfiguration extends AbstractMongoConfiguration {

    @Bean
    public Fongo fongo() {
        return new Fongo("inMemoryMongo");
    }

    @Bean
    @Override
    public Mongo mongo() {
        return fongo().getMongo();
    }

    @Bean
    @Override
    protected String getDatabaseName() {
        return "test";
    }

    @Bean
    @Override
    public MongoTemplate mongoTemplate() {
        return new MongoTemplate(mongo(), getDatabaseName());
    }

}
```
