### ISSUE TITLE
#MongoDB File specified in locations property are not present in classpath

### ISSUE THREAD

**Issue by ernestyears** [lordofthejars/nosql-unit#209]
I face up with a issue to set the classpath of @UsingDataSet location and please help me.
<img width="232" alt="MongoDB test" src="https://user-images.githubusercontent.com/26673931/93172598-79f56080-f72b-11ea-93f3-63151988495b.PNG">
As the screenshot shows, I put the JSON file under ".../testdata/" the same path as the test, but it still shows the erros below:
java.lang.IllegalArgumentException: File specified in locations property are not present in classpath, or no files matching default name are found. Valid default locations are: /de/uhh/mdbs/multistoreprototype/testdata/TestdataSetup_MongoDB.json or /de/uhh/mdbs/multistoreprototype/testdata/TestdataSetup_MongoDB#product_should_be_inserted_into_repository.json

	at com.lordofthejars.nosqlunit.core.AbstractNoSqlTestRule$1.loadDataSet(AbstractNoSqlTestRule.java:369)
	at com.lordofthejars.nosqlunit.core.AbstractNoSqlTestRule$1.evaluate(AbstractNoSqlTestRule.java:70)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

The Test is under "de.uhh.mdbs.multistoreprototype.testdata" with the name Textsetup_MongoDB.
And the JSON file "initialData.json" is under "C:\Users\Ji\IdeaProjects\mdbsprototype\src\test\java\de\uhh\mdbs\multistoreprototype\testdata"
I also tried to rename the JSON file to default name with "TestdataSetup_MongoDB#product_should_be_inserted_into_repository.json" but still does not work.
I am using Windows OS and does the OS matter?
Thank you in advance.

**Comment by fragonib** [comment]
Maybe JSON files should be located on /src/test/resources to be found on classpath

**Comment by ernestyears** [comment]
> Maybe JSON files should be located on /src/test/resources to be found on classpath

Thanks for the help. I solve it
