### ISSUE TITLE
#Redis java.lang.IllegalArgumentException: Windows System is not supported

### ISSUE THREAD

**Issue by ernestyears** [lordofthejars/nosql-unit#210]
Hi. I run NosqlUnit with redis on Windows OS (with IntelliJ IDEA ) and I downloaded a unofficial Redis (Version 3.2.100) and it worked with other tests.
When I run with NoSQLUnit, I got following info:

java.lang.IllegalArgumentException: Windows System is not supported, because there is no official Redis server for Windows.

	at com.lordofthejars.nosqlunit.redis.ManagedRedisLifecycleManager.doStart(ManagedRedisLifecycleManager.java:78)
	at com.lordofthejars.nosqlunit.core.AbstractLifecycleManager.startEngine(AbstractLifecycleManager.java:14)
	at com.lordofthejars.nosqlunit.redis.ManagedRedis.before(ManagedRedis.java:78)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

Is there any solution for it?
Thank you.

**Comment by ernestyears** [comment]
> Hi. I run NosqlUnit with redis on Windows OS and I downloaded a unofficial Redis and it worked with other tests.
> But for NosqlUnit I got following info:
> 
> java.lang.IllegalArgumentException: Windows System is not supported, because there is no official Redis server for Windows.
> 
> ```
> at com.lordofthejars.nosqlunit.redis.ManagedRedisLifecycleManager.doStart(ManagedRedisLifecycleManager.java:78)
> at com.lordofthejars.nosqlunit.core.AbstractLifecycleManager.startEngine(AbstractLifecycleManager.java:14)
> at com.lordofthejars.nosqlunit.redis.ManagedRedis.before(ManagedRedis.java:78)
> at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:44)
> at org.junit.rules.RunRules.evaluate(RunRules.java:18)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
> at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
> at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
> ```
> 
> Is there any solution for it?
> Thank you.
