### ISSUE TITLE
Fail to connect to mongo from unit test

### ISSUE THREAD

**Issue by joel-costigliola** [lordofthejars/nosql-unit#47]
Hi,

I don't know if this is the correct place to report my problem but I haven't found any mailing list to do so.

I'm trying to use nosqlunit for mongo unit test and I ran into the following error when executing a test.

**test extract** 

``` java
   @ClassRule
   public static ManagedMongoDb managedMongoDb = newManagedMongoDbRule().mongodPath("/home/joe/prog/mongo/mongodb").build();
   @Rule
   public MongoDbRule remoteMongoDbRule = newMongoDbRule().defaultManagedMongoDb("test");

   @Test
   @UsingDataSet(locations="initialData.json", loadStrategy= LoadStrategyEnum.CLEAN_INSERT)
   @ShouldMatchDataSet(location="expectedData.json")
   public void should_return_NameCollection_with_given_name() {
// test content omitted
}

```

**test error**

```
2013-01-21 19:07:36,700 - [INFO] c.l.n.m.ManagedMongoDb - Starting /home/joe/prog/mongo/mongodb MongoDb instance.
Jan 21, 2013 7:07:40 PM com.mongodb.DBTCPConnector initDirectConnection
WARNING: Exception executing isMaster command on /127.0.0.1:27017
java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
    at com.mongodb.DBPort._open(DBPort.java:214)
    at com.mongodb.DBPort.go(DBPort.java:107)
    at com.mongodb.DBPort.go(DBPort.java:88)
    at com.mongodb.DBPort.findOne(DBPort.java:143)
    at com.mongodb.DBPort.runCommand(DBPort.java:148)
    at com.mongodb.DBTCPConnector.initDirectConnection(DBTCPConnector.java:548)
    at com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:372)
    at com.mongodb.Mongo.isMongosConnection(Mongo.java:627)
    at com.mongodb.DB.wrapCommand(DB.java:294)
    at com.mongodb.DB.command(DB.java:272)
    at com.mongodb.DB.command(DB.java:256)
    at com.mongodb.DB.command(DB.java:313)
    at com.mongodb.DB.command(DB.java:211)
    at com.mongodb.DB.command(DB.java:326)
    at com.mongodb.DB.getStats(DB.java:381)
    at com.lordofthejars.nosqlunit.mongodb.MongoDbLowLevelOps.assertThatConnectionIsPossible(MongoDbLowLevelOps.java:26)
    at com.lordofthejars.nosqlunit.mongodb.ManagedMongoDbLifecycleManager.assertThatConnectionToMongoDbIsPossible(ManagedMongoDbLifecycleManager.java:179)
    at com.lordofthejars.nosqlunit.mongodb.ManagedMongoDbLifecycleManager.doStart(ManagedMongoDbLifecycleManager.java:83)
    at com.lordofthejars.nosqlunit.core.AbstractLifecycleManager.startEngine(AbstractLifecycleManager.java:12)
    at com.lordofthejars.nosqlunit.mongodb.ManagedMongoDb.before(ManagedMongoDb.java:87)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:76)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

... some error traces ommited
```

The test fails but not mongo, it turns out that a `mongod` process is running, started with the command below :

```
/home/joe/prog/mongo/mongodb/bin/mongod --dbpath mongo-dbpath --port 27017 --logpath logpath
```

One weird thing is that this command runs fine when I execute it from a bash shell (I'm under ubuntu by the way) because I'm able to connect with mongo shell.

FYI, the test method is not executed.

Any idea of what is going wrong ?

Regards,

Joel

ps : I can give full logs and unit test if you need.

**Comment by tamminh** [comment]
It took me a day to figure out how to get it works with IntelliJ! Put this to your ManagedMongoDB: 

appendSingleCommandLineArguments("--fork")

before calling build().
