### ISSUE TITLE
Can't use BinData (MongoDB) with UsingDataSet annotation

### ISSUE THREAD

**Issue by Krossnine** [lordofthejars/nosql-unit#59]
Hi Alex,

I can't use BinData (MongoDB) to populate my unit tests with UsingDataSet Annotation.
Here is a simple json document I try to import (I export it from my mongodb collection) : 

``` javascript
{
    "photo" : [
        {
            "_id" : "12345",
            "_class" : "org.krossnine.Photo",
            "ownerId" : "1",
            "approved" : false,
            "content" : { "$binary" : "FILE_CONTENT_HERE_IN_BASE_64", "$type" : "00" },
            "creationDate" : { "$date" : 1361997264500 }
        }
    ]
}
```

When I try to run my tests, I have an exception :

``` java
Caused by: java.lang.IllegalArgumentException: fields stored in the db can't start with '$' (Bad Key: '$binary')
    at com.mongodb.DBCollection.validateKey(DBCollection.java:1444)
    at com.mongodb.DBCollection._checkKeys(DBCollection.java:1410)
    at com.mongodb.DBCollection._checkKeys(DBCollection.java:1413)
    at com.mongodb.DBCollection._checkObject(DBCollection.java:1400)
    at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:243)
    at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:226)
    at com.mongodb.DBCollection.insert(DBCollection.java:75)
    at com.mongodb.DBCollection.insert(DBCollection.java:59)
    at com.mongodb.DBCollection.insert(DBCollection.java:104)
    at com.lordofthejars.nosqlunit.mongodb.DefaultInsertionStrategy.insertData(DefaultInsertionStrategy.java:93)
    at com.lordofthejars.nosqlunit.mongodb.DefaultInsertionStrategy.insertParsedData(DefaultInsertionStrategy.java:59)
    at com.lordofthejars.nosqlunit.mongodb.DefaultInsertionStrategy.insert(DefaultInsertionStrategy.java:27)
    at com.lordofthejars.nosqlunit.mongodb.DefaultInsertionStrategy.insert(DefaultInsertionStrategy.java:15)
    at com.lordofthejars.nosqlunit.core.AbstractCustomizableDatabaseOperation.executeInsertion(AbstractCustomizableDatabaseOperation.java:23)
    at com.lordofthejars.nosqlunit.mongodb.MongoOperation.insertData(MongoOperation.java:54)
    ... 28 more
```

If I remove content field, all is OK.

If you want to see what is this type, you can open this link :
http://docs.mongodb.org/manual/reference/mongodb-extended-json/

Is there a workaround for inserting BinData in MongoDB with @UsingDataSet or is it not supported yet ?

Cheers,
Jeremy

**Comment by gsmachado** [comment]
@lordofthejars: I realized that currently the "$binary" value is correctly set using @UsingDataSet, but the "$type" is not being respected. It's always being inserted as "$type" : "00" -- even though I set on my .json file "$type" : "03" (or "3"). I'm using version 0.14.0.
Any clues of what might be the problem?
